#ifndef GLOBAL_VAR_H
#define GLOBAL_VAR_H

#include "game_state.h"   ///< Game_State enum definition
#include <stdint.h>


// ===== Game state variables =====
extern Game_State state;                ///< Current state of the game state machine
extern uint8_t sequence_length;         ///< Total steps in current Simon sequence
extern uint8_t sequence_index;          ///< Current step index being played or checked
extern uint16_t playback_delay;         ///< Dynamic playback delay based on ADC or settings
extern uint16_t pin_playback_delay;     ///< Stored delay for SUCCESS_STATE
extern uint8_t step;                    ///< Step generated by LFSR for current sequence
extern uint8_t final_button_choice;     ///< Last user input (button or UART)
extern uint8_t current_sequence;        ///< Tracks sequence progression for highscore
extern uint16_t current_score;          ///< Stores final score for the completed game

#endif // GLOBAL_VAR_H
